language: elixir
elixir: 1.1.1
otp_release:
  - 18.0
sudo: false
before_script:
  - mix deps.get --only test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only docs
  - MIX_ENV=docs mix docs
